Project1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('RSVP.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

RSVP/urls.py
from django.urls import path, re_path

from . import views

app_name = 'RSVP'
urlpatterns = [path('', views.home, name='home'), re_path(r'^home/$', views.home, name='home'),
               path('registrant_list', views.registrant_list, name='registrant_list'),
               path('registrant/<int:pk>/edit/', views.registrant_edit, name='registrant_edit'),
               path('registrant/<int:pk>/delete/', views.registrant_delete, name='registrant_delete'),
               path('event_list', views.event_list, name='event_list'),
               path('event/<int:event_id>/register', views.event_registration, name='event_registration'),
               path('event/create/', views.event_new, name='event_new'),
               path('event/<int:pk>/edit/', views.event_edit, name='event_edit'),
               path('event/<int:pk>/delete/', views.event_delete, name='event_delete'),
               path('venue_list', views.venue_list, name='venue_list'),
               path('venue/create/', views.venue_new, name='venue_new'),
               path('venue/<int:pk>/edit/', views.venue_edit, name='venue_edit'),
               path('venue/<int:pk>/delete/', views.venue_delete, name='venue_delete'),
               path('registration/register/', views.register, name='register'),
               ]

RSVP/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


class Registrant(models.Model):
    Registrant_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    birth_date = models.DateField(null=True, blank=True)
    email = models.EmailField(max_length=50)
    phone_number = models.CharField(max_length=50)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zipcode = models.CharField(max_length=10)
    created_date = models.DateTimeField(
        default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.save()

    def updated(self):
        self.save()

    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)


class Venue(models.Model):
    venue_id = models.AutoField(primary_key=True)
    venue_name = models.CharField(max_length=50)
    venue_email = models.EmailField(max_length=50)
    phone_number = models.CharField(max_length=50)
    venue_address = models.CharField(max_length=200)
    venue_city = models.CharField(max_length=50)
    venue_state = models.CharField(max_length=50)
    venue_zipcode = models.CharField(max_length=10)
    created_date = models.DateTimeField(
        default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.save()

    def updated(self):
        self.save()

    def __str__(self):
        return self.venue_name


class Event(models.Model):
    event_id = models.AutoField(primary_key=True)
    event_name = models.CharField(max_length=50)
    event_date = models.DateTimeField()
    event_description = models.CharField(max_length=200)
    event_venue = models.ForeignKey(Venue, on_delete=models.PROTECT, related_name='event')
    created_date = models.DateTimeField(
        default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.save()

    def updated(self):
        self.save()

    def __str__(self):
        return self.event_name


class Rsvp(models.Model):
    registrant = models.ForeignKey(Registrant, on_delete=models.CASCADE, related_name='rsvps')
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name='rsvps')
    created_date = models.DateTimeField(
        default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.save()

    def updated(self):
        self.save()

    def save(self, *args, **kwargs):
        self.datetime_created = timezone.now()
        super().save(*args, **kwargs)

    def __str__(self):
        person = self.registrant
        return '{} {}\'s rsvp for {}'.format(person.first_name, person.last_name, self.event.event_name)

RSVP/forms.py
from django import forms
from .models import Registrant, Event, Venue


class RegistrantForm(forms.ModelForm):
    class Meta:
        model = Registrant
        fields = ('Registrant_id', 'first_name', 'last_name', 'email', 'phone_number',
                  'address', 'city', 'state', 'zipcode')


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ('event_id', 'event_name', 'event_date', 'event_description')


class VenueForm(forms.ModelForm):
    class Meta:
        model = Venue
        fields = ('venue_id', 'venue_name', 'venue_email', 'phone_number',
                  'venue_address', 'venue_city', 'venue_state', 'venue_zipcode')

RSVP/views.py
from django.contrib.auth import login
from django.shortcuts import render, get_object_or_404
from .models import *
from .forms import *
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm

now = timezone.now()


def home(request):
    return render(request, 'RSVP/home.html',
                  {'RSVP': home})


def register(request):
    form = UserCreationForm(request.POST)
    if form.is_valid():
        user = form.save()
        username = form.cleaned_data.get('username')
        login(request, user)
        return redirect("RSVP:home")
    else:
        for msg in form.error_messages:
            print(form.error_messages[msg])

    form = UserCreationForm
    return render(request=request,
                  template_name="registration/register.html",
                  context={"form": form})


@login_required
def registrant_list(request):
    registrant = Registrant.objects.filter(created_date__lte=timezone.now())
    return render(request, 'RSVP/registrant_list.html',
                  {'registrants': registrant})


@login_required
def registrant_edit(request, pk):
    registrant = get_object_or_404(Registrant, pk=pk)
    if request.method == "POST":
        # update
        form = RegistrantForm(request.POST, instance=registrant)
        if form.is_valid():
            registrant = form.save(commit=False)
            registrant.updated_date = timezone.now()
            registrant.save()
            registrant = Registrant.objects.filter(created_date__lte=timezone.now())
        return render(request, 'RSVP/registrant_list.html',
                      {'registrants': registrant})
    else:
        # edit
        form = RegistrantForm(instance=registrant)
        return render(request, 'RSVP/registrant_edit.html', {'form': form})


@login_required
def registrant_delete(request, pk):
    registrant = get_object_or_404(Registrant, pk=pk)
    registrant.delete()
    return redirect('RSVP:registrant_list')


def event_list(request):
    event = Event.objects.filter(created_date__lte=timezone.now())
    return render(request, 'RSVP/event_list.html',
                  {'events': event})


@login_required
def event_new(request):
    if request.method == "POST":
        form = EventForm(request.POST)
        if form.is_valid():
            event = form.save(commit=False)
            event.created_date = timezone.now()
            event.save()
            event = Event.objects.filter(created_date__lte=timezone.now())
            return render(request, 'RSVP/service_list.html',
                          {'events': event})
    else:
        form = EventForm()
        # print("Else")
    return render(request, 'RSVP/event_new.html', {'form': form})


@login_required
def event_edit(request, pk):
    event = get_object_or_404(Event, pk=pk)
    if request.method == "POST":
        # update
        form = EventForm(request.POST, instance=event)
        if form.is_valid():
            event = form.save(commit=False)
            event.updated_date = timezone.now()
            event.save()
            event = Event.objects.filter(created_date__lte=timezone.now())
        return render(request, 'RSVP/event_list.html',
                      {'events': event})
    else:
        # edit
        form = EventForm(instance=event)
        return render(request, 'RSVP/event_edit.html', {'form': form})


@login_required
def event_delete(request, pk):
    event = get_object_or_404(Event, pk=pk)
    event.delete()
    return redirect('RSVP:event_list')


@login_required
def event_new(request):
    if request.method == "POST":
        form = EventForm(request.POST)
        if form.is_valid():
            event = form.save(commit=False)
            event.created_date = timezone.now()
            event.save()
            event = Event.objects.filter(created_date__lte=timezone.now())
            return render(request, 'RSVP/service_list.html',
                          {'events': event})
    else:
        form = EventForm()
        # print("Else")
    return render(request, 'RSVP/event_new.html', {'form': form})


def event_registration(request, event_id):
    event = Event.objects.get(event_id=event_id)
    if request.method == "POST":
        form = RegistrantForm(request.POST)
        if form.is_valid():
            registrant = form.save(commit=False)
            registrant.created_date = timezone.now()
            registrant.save()
            registrant = Registrant.objects.filter(created_date__lte=timezone.now())
            return render(request, 'RSVP/registrant_list.html',
                          {'registrants': registrant})
    else:
        form = RegistrantForm()
        # print("Else")
    return render(request, 'RSVP/event_registration.html', {'form': form})


def venue_list(request):
    venue = Venue.objects.filter(created_date__lte=timezone.now())
    return render(request, 'RSVP/venue_list.html',
                  {'venues': venue})


@login_required
def venue_new(request):
    if request.method == "POST":
        form = VenueForm(request.POST)
        if form.is_valid():
            venue = form.save(commit=False)
            venue.created_date = timezone.now()
            venue.save()
            venues = Venue.objects.filter(created_date__lte=timezone.now())
            return render(request, 'RSVP/venue_list.html',
                          {'venues': venue})
    else:
        form = VenueForm()
        # print("Else")
    return render(request, 'RSVP/venue_new.html', {'form': form})


@login_required
def venue_edit(request, pk):
    venue = get_object_or_404(Venue, pk=pk)
    if request.method == "POST":
        # update
        form = VenueForm(request.POST, instance=venue)
        if form.is_valid():
            venue = form.save(commit=False)
            venue.updated_date = timezone.now()
            venue.save()
            venue = Venue.objects.filter(created_date__lte=timezone.now())
        return render(request, 'RSVP/venue_list.html',
                      {'venues': venue})
    else:
        # edit
        form = VenueForm(instance=venue)
        return render(request, 'RSVP/venue_edit.html', {'form': form})


@login_required
def venue_delete(request, pk):
    venue = get_object_or_404(Venue, pk=pk)
    venue.delete()
    return redirect('RSVP:venue_list')

RSVP/templates/RSVP/event_delete.html
{% extends 'RSVP/base.html' %}
<h1>Delete {{ event.event_name }}?</h1>
<form method="post">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Delete">
    <a href="{% url 'RSVP:home' pk=event.event_id %} ">Cancel</a>
</form>
{% endblock %}

RSVP/templates/RSVP/event_edit.html
{% extends 'RSVP/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h1>Edit Event</h1>
<form method="POST" class="event-form">{% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="save btn btn-default">Update</button>
</form>
{% endblock %}

RSVP/templates/RSVP/event_list.html
{% extends 'RSVP/base.html' %}
{% block content %}
<html>
<head>
    <meta charset="UTF-8">
    <title>RSVP Service</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
</head>
<body>
<style>
    body {
    background-color: beige;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-primary">
                <div class="panel-heading">Welcome!</div>
                <div class="panel-body">
                    RSVP Services!
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <a href="{% url 'RSVP:event_new' %}" class="row"><span
            class="btn btn-primary">Add Event</span></a>
    <h2 style="padding-left: 15Px">Event Information</h2>
</div>
<div>
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr class="bg-info">
            <th>Event Name</th>
            <th>Date </th>
            <th>Description</th>
            <th>Venue</th>
            <th colspan="3">Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for event in events %}
        <tr>
            <td>{{ event.event_name }}</td>
            <td>{{ event.event_date }}</td>
            <td>{{ event.event_description }}</td>
            <td>{{ event.event_venue }}</td>
            <td><a href="{% url 'RSVP:event_edit' pk=event.pk %}" class="btn btn-warning">Edit</a>
            <td><a href="{% url 'RSVP:event_delete' pk=event.pk %}"
                   onclick="return confirm('Are you sure you want to delete?')"
                   class="btn btn-danger">Delete</a>
            <td><a href="{% url 'RSVP:event_registration' event_id=event.event_id%}" class="btn btn-primary">Register</a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
</body>
</html>
{% endblock %}

RSVP/templates/RSVP/event_new.html
{% extends 'RSVP/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h1>Add a New Event</h1>
<form method="POST" class="event-form">{% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="save btn btn-default">Save</button>
</form>
{% endblock %}

RSVP/templates/RSVP/event_registration.html
{% extends 'RSVP/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="form-body">
    <h1>RSVP Services</h1>
    <h2>Register for {{event.event_name}}</h2>
    <form method="POST" class="registrant-form">{% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="save btn btn-default">Submit</button>
    </form>
</div>
{% endblock %}

RSVP/templates/RSVP/home.html
{% extends 'RSVP/base.html' %}{% load static %}{% block content %}
<html>
<body>
{% if user.is_authenticated %}
<div class="page-container"><h2 class="top-menu">Hello {{ user.username }},</h2>
    <p>Please choose from below options.</p></div>
{% endif %}
<div class="content container">
    <div class="row">
        <div class="col-md-12">
            <div class="links">                            <!-- Example row of columns -->
                <div class="row">
                    <div class="col-md-3">
                        <div class="thumbnail">
                            <img src="{% static 'images/registrant.jpg' %}" alt="registrant"/>
                            <div class="caption"><h2>Registrant</h2>
                                <p>Lets register!!</p>
                                <p><a class="btn btn-primary" href="{% url 'RSVP:registrant_list' %}" role="button">View
                                    details </a></p></div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="thumbnail">
                            <img src="{% static 'images/conference.jpg' %}" alt="events"/>
                            <div class="caption"><h2>Event</h2>
                                <p>Fun and educational Events!!</p>
                                <p><a class="btn btn-primary" href="{% url 'RSVP:event_list' %}" role="button">View
                                    details </a></p></div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="thumbnail">
                            <img src="{% static 'images/venue.jpeg' %}" alt="venue"/>
                            <div class="caption"><h2>Venues</h2>
                                <p>Great Venues!</p>
                                <p><a class="btn btn-primary" href="{% url 'RSVP:venue_list' %}" role="button">View
                                    details </a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>
{% endblock %}

RSVP/templates/RSVP/registrant_delete.html
{% extends 'RSVP/base.html' %}
{% block body_block %}
<h1>Delete {{ registrant.registrant_first_name }}?</h1>
<form method="post">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Delete">
    <a href="{% url 'RSVP:home' pk=registrant.registrant_id %} ">Cancel</a>
</form>
{% endblock %}

RSVP/templates/RSVP/registrant_edit.html
{% extends 'RSVP/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Edit Registrant</h1>
    <form method="POST" class="registrant-form">{% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}

RSVP/templates/RSVP/registrant_list.html
{% extends 'RSVP/base.html' %}
{% block content %}
<html>
<head>
    <meta charset="UTF-8">
    <title>RSVP Service</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
</head>
<body>
<style>
    body {
    background-color: beige;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-primary">
                <div class="panel-heading">Welcome!</div>
                <div class="panel-body">
                    RSVP Services!
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <h2 style="padding-left: 15Px">Registrant Information</h2>
</div>
<div>
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr class="bg-info">
            <th>FistName</th>
            <th>LastName</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Address</th>
            <th>City</th>
            <th>State</th>
            <th>ZipCode</th>
            <th colspan="2">Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for registrant in registrants %}
        <tr>
            <td>{{ registrant.first_name}}</td>
            <td>{{ registrant.last_name }}</td>
            <td>{{ registrant.email }}</td>
            <td>{{ registrant.phone_number }}</td>
            <td>{{ registrant.address }}</td>
            <td>{{ registrant.city }}</td>
            <td>{{ registrant.state }}</td>
            <td>{{ registrant.zipcode }}</td>
            <td><a href="{% url 'RSVP:registrant_edit' pk=registrant.pk %}" class="btn btn-warning">Edit</a>
            <td><a href="{% url 'RSVP:registrant_delete' pk=registrant.pk %}"
                   onclick="return confirm('Are you sure you want to delete?')"
                   class="btn btn-danger">Delete</a>
                </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
</body>
</html>
  {% endblock %}

RSVP/templates/RSVP/venue_delete.html
{% extends 'RSVP/base.html' %}
{% block body_block %}
<h1>Delete {{ venue.venue_name }}?</h1>
<form method="post">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Delete">
    <a href="{% url 'RSVP:home' pk=venue.venue_id %} ">Cancel</a>
</form>
{% endblock %}

RSVP/templates/RSVP/venue_edit.html
{% extends 'RSVP/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h1>Edit Venue</h1>
<form method="POST" class="venue-form">{% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="save btn btn-default">Update</button>
</form>
{% endblock %}

RSVP/templates/RSVP/venue_list.html
{% extends 'RSVP/base.html' %}
{% block content %}
<html>
<head>
    <meta charset="UTF-8">
    <title>RSVP Service</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
</head>
<body>
<style>
    body {
    background-color: beige;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-primary">
                <div class="panel-heading">Welcome!</div>
                <div class="panel-body">
                    RSVP Services!
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <a href="{% url 'RSVP:venue_new' %}" class="row"><span
            class="btn btn-primary">Add Venue</span></a>
    <h2 style="padding-left: 15Px">Venue Information</h2>
</div>
<div>
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr class="bg-info">
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Address</th>
            <th>City</th>
            <th>State</th>
            <th>ZipCode</th>
            <th colspan="2">Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for venue in venues %}
        <tr>
            <td>{{ venue.venue_name}}</td>
            <td>{{ venue.venue_email }}</td>
            <td>{{ venue.phone_number }}</td>
            <td>{{ venue.venue_address }}</td>
            <td>{{ venue.venue_city }}</td>
            <td>{{ venue.venue_state }}</td>
            <td>{{ venue.venue_zipcode }}</td>
            <td><a href="{% url 'RSVP:venue_edit' pk=venue.pk %}" class="btn btn-warning">Edit</a>
            <td><a href="{% url 'RSVP:venue_delete' pk=venue.pk %}"
                   onclick="return confirm('Are you sure you want to delete?')"
                   class="btn btn-danger">Delete</a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
</body>
</html>
{% endblock %}

RSVP/templates/RSVP/venue_new.html
{% extends 'RSVp/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h1>Add a New Venue</h1>
<form method="POST" class="venue-form">{% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="save btn btn-default">Save</button>
</form>
{% endblock %}